exports.WHITESOURCE_INVENTORY_NAME_KEY = 'name'
exports.WHITESOURCE_INVENTORY_VERSION_KEY = 'version'
exports.WHITESOURCE_INVENTORY_LICENSES_KEY = 'licenses'
exports.WHITESOURCE_INVENTORY_GROUPID_KEY = 'groupId'
